"""add user_type to users

Revision ID: 94e98f28ceeb
Revises: fdc806f36ebd
Create Date: 2026-06-27 19:04:43.819831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e98f28ceeb'
down_revision: Union[str, None] = 'fdc806f36ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_type_enum = sa.Enum('USER', 'INSTRUCTOR', 'ADMIN', name='user_type_enum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('user_type', user_type_enum, server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    user_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
