"""drop signature unique constraint

Revision ID: c6a7fdf176c4
Revises: 43d6577d870f
Create Date: 2026-07-15 20:37:02.771611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a7fdf176c4'
down_revision: Union[str, None] = '43d6577d870f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE saved_cards DROP CONSTRAINT IF EXISTS saved_cards_signature_key;")
    op.create_unique_constraint('uq_saved_cards_user_signature', 'saved_cards', ['user_id', 'signature'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_saved_cards_user_signature', 'saved_cards', type_='unique')
    op.create_unique_constraint('saved_cards_signature_key', 'saved_cards', ['signature'])
    # ### end Alembic commands ###
